---

- name: install openlitespeed repository
  yum: name=http://rpms.litespeedtech.com/centos/litespeed-repo-1.1-1.el6.noarch.rpm state=present

- name: install latest stable openlitespeed
  yum: name=openlitespeed state=present

- name: start openlitespeed service
  action: command /usr/local/lsws/bin/lswsctrl start
