---

- name: install openlitespeed repository
  yum: name=http://rpms.litespeedtech.com/centos/litespeed-repo-1.1-1.el6.noarch.rpm state=present

- name: install latest stable openlitespeed
  yum: name=openlitespeed state=present

- name: create vhost dir
  action: command mkdir /usr/local/lsws/vhost

- name: chown to vhost dir to suexex user
  action: command chown -R {{ suexec_user }}:{{ suexec_grou }} /usr/local/lsws/vhost

- name: backup old phpsuexec template
  action: command mv /usr/local/lsws/conf/templates/phpsuexec.xml /usr/local/lsws/conf/templates/phpsuexec.xml.bak

- name: copy my optimized phpsuexec template
  template:
    src=phpsuexec.xml.jowy
    dest=/usr/local/lsws/conf/templates/phpsuexec.xml
    owner=lsadm mode=0644

- name: restart openlitespeed service
  action: command /usr/local/lsws/bin/lswsctrl restart
