- name: install mysql python
  yum: name=MySQL-python state=present

- name: delete anonymous MariaDB for {{ ansible_hostname }}
  mysql_user: user=* host={{ ansible_hostname }} state=absent
  ignore_errors: true

- name: delete anonymouse MariaDB user for localhost
  mysql_user: user=* state=absent
  ignore_errors: true

- name: delete test db
  mysql_db: db=test state=absent
  ignore_errors: true

- name: change root password on first run
  mysql_user: login_user=root login_password="" name=root password={{ mysql_root_password }} priv=*.*:ALL,GRANT
  ignore_errors: true
